### ISSUE TITLE
Default Browser

### ISSUE THREAD

**Issue by carloswm85** [Rah1x/gotoManual#5]
Thanks for the work.

It would be great to add settings for the browser used by the extension: Chrome, Firefox, Edge, and others.

**Comment by Rah1x** [comment]
Hey buddy, thanks a lot for sending the request. I had a look but unfortunately there isnt a way to set the browser. The command I use is `vscode.open` and it doesnt allow setting any browser as far as I can tell. The browser is determined by the VSCode itself.
